### ISSUE TITLE
Need to update the link for the page

### ISSUE THREAD

**Issue by Banjerr** [papercss/React-Paper-CSS-Page#1]
i've transferred the "demo" repo over to the org's repo, and deployed to the GitHub page, but I don't have access to edit the links it seems.

https://papercss.github.io/React-Paper-CSS-Page/

**Comment by Banjerr** [comment]
@rhyneav can you help with giving me access so that I can update this?

**Comment by rhyneav** [comment]
For some reason it did not keep you as admin when you transferred the page, which I guess it Github being overly secure. I just updated you to the rightful position of admin :)

![image](https://user-images.githubusercontent.com/13633775/34910138-f045d982-f87c-11e7-9a8a-dfbd9f20b64b.png)

**Comment by Banjerr** [comment]
awesome, thanks!
